### ISSUE TITLE
Seq2Seq: Encoder output

### ISSUE THREAD

**Issue by GuichardVictor** [Doreenruirui/ACL2018_Multi_Input_OCR#2]
According to the paper:

> Similar to previous work (Bahdanau et al., 2015),
> the encoder is a bidrectional RNN (Schuster and
> Paliwal, 1997) that converts source sequence x =
> [x1, · · · , xTS] into a sequence of RNN states h =
> [h1, · · · , hTS], where hi = [−→h i,←−h i] is a concatenation of both forward and backward hidden states at time step i(1 ≤ i ≤ TS).

And according to TensorFlow documentation

> Returns:
> A tuple (outputs, output_states)

Shouldn't you use the second item of the output instead of the first one (use the hidden state)?

https://github.com/Doreenruirui/ACL2018_Multi_Input_OCR/blob/8482e047344e92c25773287834f4b1e8c5579a9b/model.py#L101-L110

**Comment by Doreenruirui** [comment]
Dear Victor,

We are using GRU as our dynamic function, according to
https://www.tensorflow.org/api_docs/python/tf/nn/rnn_cell/GRUCell
The first item is the output (and state) for each time step and the second
item is the output (and state) for the last time step.

Best,
Rui

Victor Guichard <notifications@github.com> 于2019年3月26日周二 下午3:45写道：
